### ISSUE TITLE
ERROR with all request

### ISSUE THREAD

**Issue by DirtyCajunRice** [charlesabarnes/SPFtoolbox#26]
2019/01/08 13:31:00 [error] 293#293: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  dns_get_record(): Unable to parse DNS data received in /config/www/SPFtoolbox/getAll.php on line 12" while reading response header from upstream, client: 10.0.0.3, server: spf.redacted, request: "GET /getAll.php?domain=onr.com HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "spf.redacted", referrer: "https://spf.redacted/"

i dont know if its because of the current whois error

**Comment by charlesabarnes** [comment]
Interesting.  This is different than the whois error I believe.    Can you give me some info about your environment such as PHP version and OS?

**Comment by charlesabarnes** [comment]
Just checking up on this

**Comment by charlesabarnes** [comment]
Heya, gonna close this.  Let me know if you are still running into this.
