### ISSUE TITLE
Question about meta tags.

### ISSUE THREAD

**Issue by frju365** [charlesabarnes/SPFtoolbox#34]
I have a long question : Can we get rid of useless meta tags ? 
I wanted to know what are the goal of these meta tag "http-equiv" and "pragma" because, even if I know what are the goal of this header, I don't find the reason of no using php header. :-)

I did a test and these tags are simply not working with my browser for example. I did a test : 
* with meta tags : 
![test1](https://user-images.githubusercontent.com/19982894/65820867-673dff00-e22e-11e9-9c93-5f2ba6bea500.png)

* using php header : 
![test2](https://user-images.githubusercontent.com/19982894/65820880-76bd4800-e22e-11e9-84a2-31b7db1ca00d.png)

Perhaps there is something I don't understand, but I checked on w3c website about this meta tags and I found that they doesn't recommend to use it (cf. W3C validator).

**Comment by charlesabarnes** [comment]
Hello! Initially when I included those headers I was concerned about caching since the code was kinda bad.  I wanted to be able to push up quick fixes without the responses being cached by browsers.   I am open to suggestions with how to address caching by browsers.

**Comment by frju365** [comment]
Let's close this : Fixed in https://github.com/charlesabarnes/SPFtoolbox/pull/36
