### ISSUE TITLE
Broken RPLs 

### ISSUE THREAD

**Issue by davidolrik** [charlesabarnes/SPFtoolbox#42]
The following RPLs are no longer valid:

- bl.spamcannibal.org
- rbl.megarbl.net

**Comment by R0dri** [comment]
I found the same. I managed to fix the code locally. Is this still being maintained?

**Comment by charlesabarnes** [comment]
Feel free to open a PR for this

**Comment by R0dri** [comment]
> Feel free to open a PR for this
I just made a PR in this regard
