### ISSUE TITLE
Why the tracking?

### ISSUE THREAD

**Issue by tio-trom** [charlesabarnes/SPFtoolbox#52]
https://spftoolbox.com/ my adblocker and tracker blocker are blocking a bunch of stuff. Like:
```
ajax.googleapis.com
bootstrapcdn.com
maxcdn.bootstrapcdn.com
googletagmanager.com
www.googletagmanager.com
```
Why are they needed?

**Comment by charlesabarnes** [comment]
They aren't needed exactly.  Bootstrap is for some styling helpers. I am consuming this from CDN just to avoid having to maintain the dependency in the repo. 

Also I use google analytics for analytics tracking.  Not super necessary, but useful for me to identify what regions site visitors are from.  This enables me to invest in CDNs in the relevant areas.    

Functionality still works if those scripts are blocked, so feel free to continue blocking them.

**Comment by tio-trom** [comment]
Ok I use it via Yunohost so I host SFTPtoolbox myself, and I'd like to entirely remove these https://github.com/YunoHost-Apps/spftoolbox_ynh/issues/11

**Comment by Hillside502** [comment]
googletagmanager.com remains, according to uBlock Origin.

**Comment by charlesabarnes** [comment]
Thanks for the heads up @Hillside502   Thought I had automatic deploys enabled on the new host.  

If you check again, it should be gone
